logging:
  level:
    root: INFO
    com.provectus: DEBUG
    #org.springframework.http.codec.json.Jackson2JsonEncoder: DEBUG
    #org.springframework.http.codec.json.Jackson2JsonDecoder: DEBUG
    reactor.netty.http.server.AccessLog: INFO
    org.springframework.security: DEBUG

server:
  port: 8080 #- Port in which kafka-ui will run.

kafka:
  clusters:
    -
      name: local
      bootstrapServers: localhost:9092