spring:
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: market_ticker_group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

aws:
    kinesis:
        stream-name: kin
        region: us-east-1

server:
  port: 8090
